import type { RulePack } from "../shared/types";

export const f1RulePack: RulePack = {
  id: "f1",
  label: "Formula 1",
  entities: [
    "f1",
    "formula 1",
    "formula one",
    "grand prix",
    "gp",
    "qualifying",
    "sprint race",
    "sprint",
    "race",
    "paddock",
    "grid",
    "fia",
    "verstappen",
    "norris",
    "hamilton",
    "piastri",
    "leclerc",
    "russell",
    "alonso",
    "sainz",
    "tsunoda",
    "bearman",
    "antonelli",
    "lawson",
    "hadjar",
    "hulkenberg",
    "ocon",
    "gasly",
    "stroll",
    "albon",
    "bortoleto",
    "red bull",
    "mclaren",
    "ferrari",
    "mercedes",
    "aston martin",
    "williams",
    "haas",
    "sauber",
    "racing bulls",
    "alpine"
  ],
  spoilerTerms: [
    "wins",
    "won",
    "winner",
    "victory",
    "takes victory",
    "podium",
    "pole",
    "takes pole",
    "p1",
    "p2",
    "p3",
    "dnf",
    "crash",
    "crashes",
    "crashed",
    "safety car",
    "red flag",
    "penalty",
    "fastest lap",
    "championship lead",
    "constructors",
    "drivers' standings",
    "driver standings",
    "race result",
    "results",
    "classified"
  ],
  safeTerms: [
    "preview",
    "schedule",
    "what time",
    "start time",
    "watch",
    "channel",
    "practice"
  ],
  regexes: [
    "\\bP[1-9]\\b",
    "\\bDNF\\b"
  ]
};
