import type { RulePack } from "../shared/types";
import { motorsportRegexes, motorsportSafeTerms, motorsportSpoilerTerms } from "./vocab/motorsport";

export const f1RulePack: RulePack = {
  id: "f1",
  label: "Formula 1",
  group: "Motorsport",
  description: "Formula 1 races, qualifying, sprints, drivers, and teams.",
  entities: [
    "f1",
    "formula 1",
    "formula one",
    "grand prix",
    "gp",
    "qualifying",
    "sprint race",
    "sprint",
    "race",
    "paddock",
    "grid",
    "fia",
    "verstappen",
    "norris",
    "hamilton",
    "piastri",
    "leclerc",
    "russell",
    "alonso",
    "sainz",
    "tsunoda",
    "bearman",
    "antonelli",
    "lawson",
    "hadjar",
    "hulkenberg",
    "ocon",
    "gasly",
    "stroll",
    "albon",
    "bortoleto",
    "red bull",
    "mclaren",
    "ferrari",
    "mercedes",
    "aston martin",
    "williams",
    "haas",
    "sauber",
    "racing bulls",
    "alpine"
  ],
  spoilerTerms: motorsportSpoilerTerms,
  safeTerms: motorsportSafeTerms,
  regexes: motorsportRegexes
};
