import type { RulePack } from "../shared/types";
import {
  championshipCatchUpClubs, championshipClubs2026, championsLeagueCatchUpClubs, championsLeagueClubs2026,
  footballRegexes, footballSafeTerms, footballSpoilerTerms, premierLeagueCatchUpClubs, premierLeagueClubs2026
} from "./vocab/football";

export const footballRulePack: RulePack = {
  id: "football",
  label: "General football",
  group: "Football",
  description: "General football headlines and score/result language.",
  entities: [
    "football",
    "fa cup",
    "league cup",
    "carabao cup",
    "euros",
    "euro 2028",
    "uefa",
    "fifa"
  ],
  spoilerTerms: footballSpoilerTerms,
  safeTerms: footballSafeTerms,
  regexes: footballRegexes
};

export const premierLeagueRulePack: RulePack = {
  id: "premier-league",
  label: "Premier League",
  group: "Football",
  description: "Premier League clubs and results.",
  entities: [
    "premier league",
    ...premierLeagueClubs2026,
    ...premierLeagueCatchUpClubs,
    "man city",
    "man utd",
    "spurs"
  ],
  spoilerTerms: footballSpoilerTerms,
  safeTerms: footballSafeTerms,
  regexes: footballRegexes
};

const worldCup2026SpoilerTerms = [
  ...footballSpoilerTerms,
  "eliminated",
  "eliminate",
  "eliminates",
  "knocked out",
  "knock out",
  "qualified",
  "qualifies",
  "qualify",
  "advanced",
  "advances",
  "advance",
  "through",
  "through to",
  "go through",
  "goes through",
  "went through",
  "sent through",
  "crash out",
  "crashes out",
  "crashed out",
  "topped group",
  "top group",
  "tops group",
  "top their group",
  "tops their group",
  "topped their group",
  "win group",
  "wins group",
  "won group",
  "win their group",
  "wins their group",
  "won their group",
  "reached round of 16",
  "reaches round of 16",
  "reach round of 16",
  "reached quarter-final",
  "reaches quarter-final",
  "reach quarter-final",
  "reached quarter-finals",
  "reaches quarter-finals",
  "reach quarter-finals",
  "reached semi-final",
  "reaches semi-final",
  "reach semi-final",
  "reached semi-finals",
  "reaches semi-finals",
  "reach semi-finals",
  "reached final",
  "reaches final",
  "reach final",
  "penalty shootout",
  "penalty heartbreak",
  "spot-kick heartbreak",
  "shootout heartbreak",
  "heartbreak",
  "extra time",
  "var",
  "late winner",
  "stoppage-time winner",
  "injury-time winner"
];

export const worldCup2026RulePack: RulePack = {
  id: "world-cup-2026",
  label: "World Cup 2026",
  group: "Football",
  description: "FIFA World Cup 2026 teams, tournament stages, and result spoilers.",
  entities: [
    "world cup",
    "fifa world cup",
    "2026 world cup",
    "world cup 2026",
    "fifa world cup 2026",
    "fifa world cup 26",
    "group stage",
    "round of 32",
    "knockout stage",
    "knockouts",
    "last 32",
    "last-32",
    "round of 16",
    "quarter-final",
    "quarter-finals",
    "semi-final",
    "semi-finals",
    "third-place play-off",
    "world cup final",
    "canada",
    "mexico",
    "united states",
    "usa",
    "usmnt",
    "south africa",
    "south korea",
    "korea republic",
    "czechia",
    "czech republic",
    "bosnia and herzegovina",
    "bosnia",
    "qatar",
    "switzerland",
    "brazil",
    "selecao",
    "morocco",
    "haiti",
    "scotland",
    "tartan army",
    "paraguay",
    "australia",
    "socceroos",
    "turkey",
    "turkiye",
    "germany",
    "curacao",
    "ivory coast",
    "cote d'ivoire",
    "ecuador",
    "netherlands",
    "holland",
    "japan",
    "samurai blue",
    "sweden",
    "tunisia",
    "belgium",
    "egypt",
    "iran",
    "new zealand",
    "spain",
    "cape verde",
    "cabo verde",
    "saudi arabia",
    "uruguay",
    "france",
    "les bleus",
    "senegal",
    "iraq",
    "norway",
    "argentina",
    "algeria",
    "austria",
    "jordan",
    "portugal",
    "dr congo",
    "congo dr",
    "democratic republic of congo",
    "uzbekistan",
    "colombia",
    "england",
    "england football",
    "three lions",
    "croatia",
    "ghana",
    "panama"
  ],
  spoilerTerms: Array.from(new Set(worldCup2026SpoilerTerms)),
  safeTerms: footballSafeTerms,
  regexes: [
    ...footballRegexes,
    "\\btop(?:s|ped)?\\s+(?:their\\s+)?group\\s+[a-l]\\b",
    "\\b(?:win|wins|won)\\s+(?:their\\s+)?group\\s+[a-l]\\b",
    "\\b(?:through|advance(?:s|d)?|qualif(?:y|ies|ied))\\s+to\\s+(?:the\\s+)?(?:round of 32|last[-\\s]32|round of 16|quarter-finals?|semi-finals?|final)\\b",
    "\\breach(?:es|ed)?\\s+(?:the\\s+)?(?:round of 32|last[-\\s]32|round of 16|quarter-finals?|semi-finals?|final)\\b",
    "\\bpenalt(?:y|ies)\\s+(?:shootout\\s+)?heartbreak\\b",
    "\\bspot-kick\\s+heartbreak\\b"
  ]
};

export const championshipRulePack: RulePack = {
  id: "championship",
  label: "Championship",
  group: "Football",
  description: "EFL Championship clubs and results.",
  entities: [
    "championship",
    "efl championship",
    ...championshipClubs2026,
    ...championshipCatchUpClubs,
    "qpr",
    "west brom",
    "west ham",
    "wolves"
  ],
  spoilerTerms: footballSpoilerTerms,
  safeTerms: footballSafeTerms,
  regexes: footballRegexes
};

export const championsLeagueRulePack: RulePack = {
  id: "champions-league",
  label: "Champions League",
  group: "Football",
  description: "UEFA Champions League results and knockout stories.",
  entities: [
    "champions league",
    "uefa champions league",
    "ucl",
    ...championsLeagueClubs2026,
    ...championsLeagueCatchUpClubs,
    "psg",
    "paris saint germain",
    "man city",
    "man utd",
    "bodo/glimt",
    "bodo glimt",
    "bodø glimt",
    "psv eindhoven",
    "slavia prague"
  ],
  spoilerTerms: footballSpoilerTerms,
  safeTerms: footballSafeTerms,
  regexes: footballRegexes
};

export const englandFootballRulePack: RulePack = {
  id: "england-football",
  label: "England football",
  group: "Football",
  description: "England men's and women's national football results.",
  entities: [
    "england",
    "england football",
    "three lions",
    "lionesses",
    "euro 2028",
    "world cup qualifier",
    "nations league"
  ],
  spoilerTerms: footballSpoilerTerms,
  safeTerms: footballSafeTerms,
  regexes: footballRegexes
};
